### ISSUE TITLE
No PTZ on move command

### ISSUE THREAD

**Issue by estoyarto** [marklagendijk/node-onvif-ptz-cli#5]
Hi!
Thanks for creating this program, without it I could not control my camera without its official app. The only problem I have is the Move command does not move the camera.  I can do it with goto-preset without problems.
I use this command line
onvif-ptz move --baseUrl = http: //192.168.88.43: 80 -u = admin -p = xxxxx -x = 0.01

But nothing happens when executing it, it does not show an error or anything.
Maybe it has to do with the onvif protocol option of Continuous Move and Relative Move?
Because in the onvif device manager I can do it without problems but if the Continuous Move option is selected.
Thanks again!

**Comment by marklagendijk** [comment]
Currently this library only supports relative move, so it could indeed be the issue.
